version: 1.2
workflows:
  - name: AnnotateDeNovo
    subclass: WDL
    primaryDescriptorPath: /wdl/AnnotateDeNovo.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: PlotCNVEvidence
    subclass: WDL
    primaryDescriptorPath: /wdl/PlotCNVEvidence.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
