version: 1.2
workflows:
  - name: AnnotateDeNovo
    subclass: WDL
    primaryDescriptorPath: /wdl/AnnotateDeNovo.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: PlotDeNovoEvidence
    subclass: WDL
    primaryDescriptorPath: /wdl/PlotDeNovoEvidence.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: FixDCR
    subclass: WDL
    primaryDescriptorPath: /wdl/FixDCR.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: CheckPloidy
    subclass: WDL
    primaryDescriptorPath: /wdl/CheckPloidy.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: CheckSex
    subclass: WDL
    primaryDescriptorPath: /wdl/CheckSex.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
