version: 1.2
workflows:
  - name: AnnotateDeNovo
    subclass: WDL
    primaryDescriptorPath: /wdl/AnnotateDeNovo.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: PlotDeNovoEvidence
    subclass: WDL
    primaryDescriptorPath: /wdl/PlotDeNovoEvidence.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: MakePloidyMatrix
    subclass: WDL
    primaryDescriptorPath: /wdl/MakePloidyMatrix.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: FixDCR
    subclass: WDL
    primaryDescriptorPath: /wdl/FixDCR.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - name: PlotPloidy
    subclass: WDL
    primaryDescriptorPath: /wdl/PlotPloidy.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
